# Generated by Django 6.1.1 on 2026-09-15 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=20, unique=True, verbose_name='ID del activo')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('engine_number', models.CharField(blank=True, max_length=100, verbose_name='Número de motor')),
                ('manufacturing_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fabricación')),
                ('internal_inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Número de inventario interno')),
                ('owner', models.CharField(blank=True, max_length=200, verbose_name='Propietario')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('physical_condition', models.CharField(choices=[('new', 'Nuevo'), ('good', 'Bueno'), ('regular', 'Regular'), ('bad', 'Malo'), ('repair', 'En reparación'), ('out_of_service', 'Fuera de servicio')], default='regular', max_length=30, verbose_name='Condición física')),
                ('identification_status', models.CharField(choices=[('identified', 'Identificado'), ('partial', 'Parcialmente identificado'), ('pending', 'Pendiente de identificación'), ('duplicate', 'Duplicado por confirmar')], default='pending', max_length=30, verbose_name='Estatus de identificación')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('location_type', models.CharField(choices=[('warehouse', 'Bodega'), ('project', 'Obra'), ('workshop', 'Taller'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de ubicación')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('general', 'Foto general'), ('plate', 'Placa de identificación'), ('serial', 'Número de serie'), ('engine', 'Motor'), ('condition', 'Condición física'), ('other', 'Otra')], max_length=30, verbose_name='Tipo de fotografía')),
                ('image', models.ImageField(upload_to='assets/%Y/%m/', verbose_name='Fotografía')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.asset', verbose_name='Activo')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.brand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.category', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('ownership', 'Documento de propiedad'), ('purchase', 'Comprobante de compra'), ('import', 'Documento de importación'), ('warranty', 'Garantía'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Número de documento')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='inventory.asset', verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_types', to='inventory.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Tipo de equipo',
                'verbose_name_plural': 'Tipos de equipo',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.equipmenttype', verbose_name='Tipo de equipo'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('transfer', 'Transferencia'), ('return', 'Regreso de obra'), ('maintenance', 'Envío a mantenimiento')], max_length=30, verbose_name='Tipo de movimiento')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('condition_out', models.CharField(blank=True, max_length=30, verbose_name='Condición al salir')),
                ('condition_in', models.CharField(blank=True, max_length=30, verbose_name='Condición al regresar')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de regreso')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.asset', verbose_name='Activo')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_destination', to='inventory.location', verbose_name='Ubicación destino')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_origin', to='inventory.location', verbose_name='Ubicación origen')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-movement_date'],
            },
        ),
    ]
