# Generated by Django 6.1.1 on 2026-09-15 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ejemplo: OB-0001', max_length=30, unique=True, verbose_name='Código de obra')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la obra')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('estimated_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de terminación')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha real de terminación')),
                ('status', models.CharField(choices=[('planned', 'Planeada'), ('in_progress', 'En proceso'), ('completed', 'Terminada'), ('cancelled', 'Cancelada')], default='planned', max_length=30, verbose_name='Estatus')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.clientprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(verbose_name='Fecha de asignación')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de regreso')),
                ('condition_out', models.CharField(blank=True, max_length=30, verbose_name='Condición al salir')),
                ('condition_in', models.CharField(blank=True, max_length=30, verbose_name='Condición al regresar')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='inventory.asset', verbose_name='Activo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='project.project', verbose_name='Obra')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_asset_assignments', to='accounts.employeeprofile', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Asignación de activo',
                'verbose_name_plural': 'Asignaciones de activos',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
